#ifndef CONSTS_H
#define CONSTS_H
#define SCREEN_WIDTH 1280
#define HEIGHT 960
#define SIM_DIM 800 
#define SIM_MAX_WIDTH_COORD 960 
#define SIM_MIN_WIDTH_COORD 160
#define SIM_MAX_HEIGHT_COORD 800 
#define SIM_MIN_HEIGHT_COORD 0
#define FPS 144
#define THREADS 6
#define DEFAULT_PARTICLES 100
#define MAX_PARTICLES 3000
#define DEFAULT_DT 1.0f/60
#define SOFTENING 0.1f
#define ELASTICITY 1.0f
#define PERCENT_CORRECTION 0.5f
#define DEFAULT_GRAVITY 9.8f
#endif //CONSTS_H
