#ifndef CONSTS_H
#define CONSTS_H
#define WIDTH 1280
#define HEIGHT 960
#define FPS 60
#define DEFAULT_PARTICLES 1000
#define DEFAULT_DT 1./60
#define ELASTICITY 1.
#define PERCENT_CORRECTION 0.5
#define DEFAULT_GRAVITY 9.8
#endif //CONSTS_H
